version: '2'

services:
  voting-app:
    image: vieux/demo-vote
    ports:
      - "80"
    networks:
      - vote

  redis:
    image: redis
    networks:
      - vote

  worker:
    image: vieux/demo-worker
    networks:
      - vote

  db:
    image: postgres:9.4
    networks:
      - vote
      - result

  result-app:
    image: vieux/demo-result
    ports:
      - "80"
    networks:
      - result

networks:
  vote:
    driver: overlay
  result:
    driver: overlay